// frontend/src/components/GuessInput.tsx
import { createSignal, Component } from 'solid-js';
import { PrimaryButton } from './buttons/PrimaryButton';

interface GuessInputProps {
    onGuess: (guess: string) => void;
}

const GuessInput: Component<GuessInputProps> = ({ onGuess }) => {
    const [currentGuess, setCurrentGuess] = createSignal('');

    const handleSubmit = (e: Event) => {
        e.preventDefault();
        const guessToSend = currentGuess().trim();
        if (guessToSend) {
            onGuess(guessToSend);
            setCurrentGuess('');
        }
    };

    return (
        <form onSubmit={handleSubmit} class="flex gap-2">
            <input
                type="text"
                value={currentGuess()}
                onInput={(e) => setCurrentGuess((e.target as HTMLInputElement).value)}
                placeholder="Enter your guess"
                maxLength={50}
                class="flex-1 rounded border border-gray-300 p-2 transition duration-150 ease-in-out focus:ring-2 focus:ring-blue-500 focus:outline-none"
                aria-label="Enter your guess"
            />
            <PrimaryButton
                type="submit"
                disabled={!currentGuess().trim()}
                class="flex-0"
            >
                Guess
            </PrimaryButton>
        </form>
    );
};

export default GuessInput;

// frontend/src/components/GuessInput.jsx
import React, { useState } from 'react';

function GuessInput({ onGuess }) {
	const [currentGuess, setCurrentGuess] = useState('');

	const handleSubmit = (e) => {
		e.preventDefault();
		const guessToSend = currentGuess.trim();
		if (guessToSend) {
			onGuess(guessToSend);
			setCurrentGuess(''); // Clear input
		}
	};

	return (
		<form onSubmit={handleSubmit} className="flex gap-2">
			<input
				type="text"
				value={currentGuess}
				onChange={(e) => setCurrentGuess(e.target.value)}
				placeholder="Enter your guess"
				maxLength="50"
				className="flex-grow p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 transition duration-150 ease-in-out"
				aria-label="Enter your guess"
			/>
			<button
				type="submit"
				className="px-4 py-2 bg-blue-500 text-black font-medium rounded hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-1 transition duration-150 ease-in-out disabled:opacity-50 disabled:cursor-not-allowed"
				disabled={!currentGuess.trim()}
			>
				Guess
			</button>
		</form>
	);
}

export default GuessInput;
