// frontend/src/components/WordDisplay.jsx
import React from 'react';

function WordDisplay({ word = '', blanks = '', length = 0 }) {
	return (
		<div className="text-2xl lg:text-3xl font-semibold tracking-widest text-center p-2 rounded bg-gray-200 min-h-[3rem] flex items-center justify-center select-none">
			{word ? (
				<span>{word}</span>
			) : blanks ? (
				<>
					<span className="mr-2">{blanks}</span>
					<span className="text-sm text-gray-600">({length} letters)</span>
				</>
			) : (
				<span className="text-gray-400">&nbsp;</span>
			)}
		</div>
	);
}

export default WordDisplay;

// frontend/src/components/WordDisplay.tsx
import { Show } from 'solid-js';

interface WordDisplayProps {
    word?: string;
    blanks?: string;
    length?: number;
}

function WordDisplay(props: WordDisplayProps) {
    const word = () => props.word || '';
    const blanks = () => props.blanks || '';
    const length = () => props.length || 0;

    return (
        <div class="flex min-h-[3rem] items-center justify-center rounded bg-gray-200 p-2 text-center text-2xl font-semibold tracking-widest select-none lg:text-3xl">
            <Show
                when={word()}
                fallback={
                    <Show
                        when={blanks()}
                        fallback={<span class="text-gray-400">&nbsp;</span>}
                    >
                        <span class="mr-2">{blanks()}</span>
                        <span class="text-sm text-gray-600">
                            ({length()} letters)
                        </span>
                    </Show>
                }
            >
                <span>{word()}</span>
            </Show>
        </div>
    );
}

export default WordDisplay;
