// frontend/src/App.jsx
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { useWebSocket } from './hooks/useWebSocket'; // Import the custom hook

// Import components
import NameInput from './components/NameInput';
import PlayerList from './components/PlayerList';
import ChatBox from './components/ChatBox';
import Whiteboard from './components/Whiteboard';
import WordDisplay from './components/WordDisplay';
import TimerDisplay from './components/TimerDisplay';
import GuessInput from './components/GuessInput';
import StatusMessage from './components/StatusMessage';

const MIN_PLAYERS = 2;

function App() {
	console.log("App component rendering...");

	// --- WebSocket Connection ---
	const { isConnected, lastMessage, sendMessage, connect } = useWebSocket();

	// --- Game State ---
	const [appState, setAppState] = useState('connecting'); // 'connecting', 'enterName', 'joining', 'waiting', 'active'
	const [localPlayerId, setLocalPlayerId] = useState(null);
	const [localPlayerName, setLocalPlayerName] = useState('');
	const [players, setPlayers] = useState([]); // {id, name, isHost, hasGuessedCorrectly}
	const [hostId, setHostId] = useState(null);
	const [currentDrawerId, setCurrentDrawerId] = useState(null);
	const [secretWord, setSecretWord] = useState('');
	const [wordLength, setWordLength] = useState(0);
	const [statusText, setStatusText] = useState('Connecting to server...');
	const [whiteboardKey, setWhiteboardKey] = useState(Date.now()); // For resetting whiteboard
	const [chatMessages, setChatMessages] = useState([]);
	const [turnEndTime, setTurnEndTime] = useState(null);

	// --- Refs ---
	// Ref for whiteboard component instance methods (like clearCanvas) - less common in React
	// We'll handle clearing via the key prop instead.

	// --- Derived State (Memoized) ---
	const isLocalPlayerHost = useMemo(() => localPlayerId && hostId && localPlayerId === hostId, [localPlayerId, hostId]);
	const isLocalPlayerDrawer = useMemo(() => localPlayerId && currentDrawerId && localPlayerId === currentDrawerId, [localPlayerId, currentDrawerId]);
	const canLocalPlayerGuess = useMemo(() => {
		if (appState !== 'active' || !localPlayerId || !currentDrawerId || localPlayerId === currentDrawerId || !Array.isArray(players)) {
			return false;
		}
		const localPlayer = players.find(p => p?.id === localPlayerId);
		return !localPlayer?.hasGuessedCorrectly;
	}, [appState, localPlayerId, currentDrawerId, players]);
	const canHostStartGame = useMemo(() => isLocalPlayerHost && appState === 'waiting' && players.length >= MIN_PLAYERS, [isLocalPlayerHost, appState, players]);

	// --- Utility Functions ---
	const addChatMessage = useCallback((msgPayload) => {
		setChatMessages(prevMessages => {
			const newMessages = [...prevMessages, msgPayload];
			// Limit chat history
			return newMessages.length > 100 ? newMessages.slice(-100) : newMessages;
		});
	}, []); // No dependencies, safe to memoize

	const getWordBlanks = useCallback((length) => {
		if (length <= 0) return '';
		return Array(length).fill('_').join(' ');
	}, []); // No dependencies

	const updateStatusText = useCallback(() => {
		setAppState(currentAppState => { // Use functional update to get latest state
			let newStatus = statusText; // Start with current status

			if (currentAppState === 'waiting' || currentAppState === 'joining') {
				const host = players.find(p => p.isHost);
				const hostName = host ? host.name : "Someone";
				if (players.length < MIN_PLAYERS) {
					newStatus = `Waiting for more players... (${players.length}/${MIN_PLAYERS})`;
				} else if (isLocalPlayerHost) {
					newStatus = `You are the host. Start the game when ready! (${players.length} players)`;
				} else {
					newStatus = `Waiting for ${hostName} (Host) to start the game... (${players.length} players)`;
				}
				if (currentAppState === 'joining') newStatus = 'Joining game... Please wait.';
			} else if (currentAppState === 'active') {
				const drawer = players.find(p => p.id === currentDrawerId);
				const drawerName = drawer ? drawer.name : 'Someone';
				if (isLocalPlayerDrawer) {
					newStatus = `Your turn! Draw: ${secretWord}`;
				} else {
					const localPlayer = players.find(p => p.id === localPlayerId);
					if (localPlayer?.hasGuessedCorrectly) {
						newStatus = `You guessed it! Waiting for others... (${drawerName} is drawing)`;
					} else {
						newStatus = `${drawerName} is drawing! Guess the word!`;
					}
				}
			}
			// Only update if status actually changed
			if (newStatus !== statusText) {
				setStatusText(newStatus);
			}
			return currentAppState; // Return current state, no change here
		});
	}, [players, appState, isLocalPlayerHost, currentDrawerId, isLocalPlayerDrawer, secretWord, localPlayerId, statusText]); // Add dependencies

	// --- Effect for Connection Status ---
	useEffect(() => {
		if (isConnected) {
			if (appState === 'connecting') {
				console.log("WebSocket connected, moving to enterName state.");
				setAppState('enterName');
				setStatusText('Please enter your name.');
			}
		} else {
			if (appState !== 'connecting') {
				console.log("WebSocket disconnected.");
				setAppState('connecting');
				setStatusText('Disconnected. Trying to reconnect...');
				// Reset state
				setLocalPlayerId(null);
				setLocalPlayerName('');
				setPlayers([]);
				setHostId(null);
				setCurrentDrawerId(null);
				setSecretWord('');
				setWordLength(0);
				setChatMessages([]);
				setTurnEndTime(null);
				// Optional: Attempt reconnect
				// setTimeout(connect, 5000);
			}
		}
	}, [isConnected, appState, connect]); // Add connect dependency

	// --- Effect for Handling Messages ---
	useEffect(() => {
		if (lastMessage) {
			console.log("Processing message in useEffect:", lastMessage);
			const message = lastMessage; // Process the message

			switch (message.type) {
				case 'gameInfo': {
					const payload = message.payload;
					if (!payload) { console.error("Received gameInfo with null payload"); break; }
					setLocalPlayerId(payload.yourId || null);
					setPlayers(payload.players || []);
					setHostId(payload.hostId || null);
					setCurrentDrawerId(payload.currentDrawerId || null);
					setWordLength(payload.wordLength || 0);
					setTurnEndTime(payload.turnEndTime || null);
					setSecretWord(''); // Word comes via turnStart

					if (payload.isGameActive) {
						setAppState('active');
					} else {
						setAppState('waiting');
					}
					console.log("Processed gameInfo. New State:", payload.isGameActive ? 'active' : 'waiting', "localId:", payload.yourId);
					break;
				}
				case 'playerUpdate': {
					const payload = message.payload;
					if (!payload) { console.error("Received playerUpdate with null payload"); break; }
					setPlayers(payload.players || []);
					setHostId(payload.hostId || hostId); // Update host ID
					// Check if game should end due to player count (backend also handles this)
					setAppState(currentAppState => {
						if (currentAppState === 'active' && (payload.players?.length ?? 0) < MIN_PLAYERS) {
							console.log("Player count dropped below minimum, returning to waiting state.");
							setCurrentDrawerId(null);
							setTurnEndTime(null);
							setWordLength(0);
							setSecretWord('');
							return 'waiting';
						}
						return currentAppState;
					});
					break;
				}
				case 'turnStart': {
					const payload = message.payload;
					if (!payload) { console.error("Received turnStart with null payload"); break; }
					setCurrentDrawerId(payload.currentDrawerId);
					setWordLength(payload.wordLength);
					setSecretWord(payload.word || ''); // Will be empty if not drawer
					setPlayers(payload.players || players); // Update player list (resets guess status)
					setHostId(payload.players?.find(p => p.isHost)?.id || hostId); // Update host from list
					setTurnEndTime(payload.turnEndTime);
					setAppState('active');
					setWhiteboardKey(Date.now()); // Reset whiteboard
					break;
				}
				case 'playerGuessedCorrectly': {
					const payload = message.payload;
					if (!payload) { console.error("Received playerGuessedCorrectly with null payload"); break; }
					const { playerId } = payload;
					setPlayers(prevPlayers =>
						prevPlayers.map(p =>
							p.id === playerId ? { ...p, hasGuessedCorrectly: true } : p
						)
					);
					const guesser = players.find(p => p.id === playerId); // Use current players state
					if (guesser) {
						addChatMessage({ senderName: 'System', message: `${guesser.name} guessed the word!`, isSystem: true });
					}
					break;
				}
				case 'chat': {
					const payload = message.payload;
					if (!payload) { console.error("Received chat with null payload"); break; }
					addChatMessage(payload);
					break;
				}
				case 'drawEvent': {
					const payload = message.payload;
					if (!payload) { break; }
					// Need a way to pass this to Whiteboard without prop drilling excessively
					// For now, maybe use a temporary state or event emitter?
					// Or Whiteboard could consume lastMessage directly (less ideal)
					// Let's skip direct handling here and assume Whiteboard handles it via props/context later
					// console.log("Draw event received, needs handling in Whiteboard");
					break;
				}
				case 'turnEnd': {
					const payload = message.payload;
					if (!payload) { console.error("Received turnEnd with null payload"); break; }
					setTurnEndTime(null);
					if (localPlayerId !== currentDrawerId) { // Check if local player wasn't the drawer
						setWordLength(0);
					}
					// Add system message revealing word (backend already does this via chat)
					// addChatMessage({ senderName: 'System', message: `Word was: ${payload.correctWord}`, isSystem: true });
					setStatusText(`Word was: ${payload.correctWord}. Getting next turn ready...`);
					// Clear visual guess status
					setPlayers(prevPlayers => prevPlayers.map(p => ({ ...p, hasGuessedCorrectly: false })));
					break;
				}
				case 'error': {
					const payload = message.payload;
					if (!payload) { console.error("Received error with null payload"); break; }
					setStatusText(`Error: ${payload.message || 'Unknown error'}`);
					addChatMessage({ senderName: 'System', message: `Error: ${payload.message || 'Unknown error'}`, isSystem: true });
					break;
				}
				default:
					console.warn("Received unhandled message type:", message.type);
			}
		}
	}, [lastMessage, addChatMessage, players, localPlayerId, currentDrawerId, hostId]); // Add dependencies

	// --- Effect to update status text whenever relevant state changes ---
	useEffect(() => {
		updateStatusText();
	}, [appState, players, currentDrawerId, hostId, isLocalPlayerHost, isLocalPlayerDrawer, secretWord, localPlayerId, updateStatusText]); // Dependencies for status text


	// --- Event Handlers ---
	const handleNameSet = useCallback((name) => {
		console.log("handleNameSet called with name:", name);
		if (name && isConnected) {
			setLocalPlayerName(name); // Store locally
			sendMessage('setName', { name: name }); // Send to backend
			setAppState('joining'); // Move to intermediate state
			setStatusText('Joining game... Please wait.');
			console.log("Sent setName, moved state to 'joining'.");
		} else {
			console.error("Cannot set name - invalid name or WebSocket disconnected.");
			setStatusText("Failed to set name. Please check connection and try again.");
		}
	}, [isConnected, sendMessage]); // Dependencies

	const handleDraw = useCallback((drawData) => {
		if (isLocalPlayerDrawer && appState === 'active') {
			sendMessage('drawEvent', drawData);
		}
	}, [isLocalPlayerDrawer, appState, sendMessage]);

	const handleGuess = useCallback((guess) => {
		if (canLocalPlayerGuess) {
			sendMessage('guess', { guess: guess });
		}
	}, [canLocalPlayerGuess, sendMessage]);

	const handleStartGame = useCallback(() => {
		console.log("Start Game button clicked by host.");
		if (canHostStartGame) {
			sendMessage('startGame', null);
			setStatusText("Starting game...");
		} else {
			console.warn("Start game attempted but conditions not met.");
		}
	}, [canHostStartGame, sendMessage]);

	// --- Render Logic ---
	return (
		<main className="flex flex-col items-center justify-start min-h-screen bg-gray-100 p-4 font-sans">
			<h1 className="text-3xl font-bold mb-4 text-blue-600 flex-shrink-0">Scribblio Clone (React)</h1>

			{appState === 'enterName' ? (
				<>
					<NameInput onNameSet={handleNameSet} />
					<StatusMessage message={statusText} />
				</>
			) : !isConnected && appState !== 'enterName' ? (
				<div className="text-center mt-10">
					<StatusMessage message={statusText} />
					{/* Optional: Add reconnect button */}
					{/* <button onClick={connect} className="mt-4 ...">Reconnect</button> */}
				</div>
			) : (
				<>
					{appState === 'joining' || !localPlayerId ? (
						<div className="text-center mt-10">
							<StatusMessage message={statusText} />
							<p className="text-gray-500 animate-pulse mt-2">Waiting for server info...</p>
						</div>
					) : (
						// Main Game Layout
						<div className="flex flex-col lg:flex-row w-full max-w-6xl gap-4 flex-grow">
							{/* Left Panel */}
							<aside className="w-full lg:w-1/4 bg-white shadow-lg rounded-lg p-4 flex flex-col gap-4 order-2 lg:order-1 overflow-hidden max-h-[calc(100vh-8rem)]">
								<h2 className="text-xl font-semibold border-b pb-2 flex-shrink-0">Players ({players.length})</h2>
								<div className="flex-shrink overflow-y-auto mb-4 min-h-0">
									<PlayerList players={players} currentDrawerId={currentDrawerId} hostId={hostId} />
								</div>

								{canHostStartGame && (
									<button
										onClick={handleStartGame}
										className="px-4 py-2 bg-green-500 text-black font-semibold rounded hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-1 transition duration-150 ease-in-out flex-shrink-0"
									>
										Start Game ({players.length} players)
									</button>
								)}

								<h2 className={`text-xl font-semibold border-b pb-2 flex-shrink-0 ${!canHostStartGame ? 'mt-auto' : ''}`}>Chat</h2>
								<div className="flex-grow overflow-y-hidden min-h-0">
									<ChatBox messages={chatMessages} />
								</div>
							</aside>

							{/* Center Panel */}
							<section className="w-full lg:w-3/4 bg-white shadow-lg rounded-lg p-6 flex flex-col order-1 lg:order-2">
								{/* Top Bar */}
								<div className="flex justify-between items-center mb-4 gap-4 flex-shrink-0">
									<div className="flex-1 text-center min-w-0">
										{(isLocalPlayerDrawer && appState === 'active') ? (
											<WordDisplay word={secretWord} />
										) : (appState === 'active' && currentDrawerId) ? (
											<WordDisplay blanks={getWordBlanks(wordLength)} length={wordLength} />
										) : (
											<div className="h-8 md:h-10"></div>
										)}
									</div>
									<div className="w-20 text-right flex-shrink-0">
										{(appState === 'active' && turnEndTime) && (
											<TimerDisplay endTime={turnEndTime} />
										)}
									</div>
								</div>

								{/* Whiteboard */}
								<div className="mb-4 border-2 border-black rounded overflow-hidden aspect-video bg-white flex-grow">
									<Whiteboard
										key={whiteboardKey} // Use key to force reset
										isDrawer={isLocalPlayerDrawer}
										onDraw={handleDraw}
										// Need to pass draw events received from WS to Whiteboard
										// This is tricky without context/emitter. For now, Whiteboard might need access to lastMessage.
										lastDrawEvent={lastMessage?.type === 'drawEvent' ? lastMessage.payload : null}
										localPlayerIsDrawer={isLocalPlayerDrawer} // Pass explicitly
									/>
								</div>

								{/* Status */}
								<div className="mb-4 text-center flex-shrink-0">
									<StatusMessage message={statusText} />
								</div>

								{/* Guess Input */}
								<div className="flex-shrink-0">
									{canLocalPlayerGuess && (
										<GuessInput onGuess={handleGuess} />
									)}
								</div>
							</section>
						</div>
					)}
				</>
			)}
		</main>
	);
}

export default App;

// frontend/src/App.svelte
<script>
	import { onMount } from 'svelte';
	// Import stores and functions from the WebSocket module
	import { ws, wsConnected, lastMessage, connectWebSocket, sendMessage } from './lib/websocket.js';
	// Import child components
	import Whiteboard from './lib/Whiteboard.svelte';
	import WordDisplay from './lib/WordDisplay.svelte';
	import GuessInput from './lib/GuessInput.svelte';
	import StatusMessage from './lib/StatusMessage.svelte';

	// --- Component State ---
	let gameState = 'connecting'; // Overall game state: 'connecting', 'waiting', 'drawing', 'guessing', 'gameOver'
	let playerRole = null; // Player's role: null, 'drawer', 'guesser'
	let secretWord = ''; // The word to be drawn (for drawer)
	let wordLength = 0; // Length of the word (for guesser)
	let gameOverInfo = null; // Stores details when game ends: { correct: boolean, word: string }
	let statusText = 'Connecting to server...'; // User-facing status message
	let whiteboardKey = Date.now(); // Key to force re-rendering of the Whiteboard component

	// --- Component Reference ---
	let whiteboardComponent; // Reference to the Whiteboard child component instance (for calling methods)

	// --- Lifecycle ---
	onMount(() => {
		// Initiate WebSocket connection when the App component mounts
		connectWebSocket();
	});

	// --- Reactive Logic ---

	// React to changes in WebSocket connection status ($wsConnected store)
	$: if ($wsConnected) {
		// Actions when connection is established
		if (gameState === 'connecting') {
			// If we were in the initial connecting state, we now wait for the backend
			// to send us a 'waiting' or 'assignRole' message.
			// statusText = 'Connected! Waiting for server...'; // Optional intermediate state
		}
	} else {
		// Actions when connection is lost
		if (gameState !== 'connecting') { // Avoid resetting if already 'connecting'
			gameState = 'connecting'; // Reset game state
			statusText = 'Disconnected. Trying to reconnect...'; // Update status
			// Reset player-specific states
			playerRole = null;
			secretWord = '';
			wordLength = 0;
			gameOverInfo = null;
			// Optional: Implement automatic reconnection attempt trigger here
			// setTimeout(connectWebSocket, 5000); // Example: Try reconnecting after 5 seconds
		}
	}

	// React to new messages received via WebSocket ($lastMessage store)
	$: if ($lastMessage) {
		// Process the latest message
		handleMessage($lastMessage);
	}

	// --- Message Handling ---

	/**
	 * Processes incoming messages from the WebSocket server and updates component state.
	 * @param {object} message - The parsed message object { type: string, payload: object }.
	 */
	function handleMessage(message) {
		console.log("Handling message in App.svelte:", message); // For debugging
		switch (message.type) {
			case 'waiting':
				gameState = 'waiting';
				statusText = 'Waiting for another player...';
				playerRole = null; // Ensure no role is assigned
				gameOverInfo = null; // Clear previous game over info
				whiteboardKey = Date.now(); // Force whiteboard reset
				break;
			case 'assignRole':
				// Assign role based on payload
				playerRole = message.payload.role;
				if (playerRole === 'drawer') {
					secretWord = message.payload.word;
					wordLength = 0; // Clear guesser-specific state
					gameState = 'drawing';
					statusText = 'You are the Drawer! Draw the word.';
				} else if (playerRole === 'guesser') {
					secretWord = ''; // Clear drawer-specific state
					wordLength = message.payload.wordLength;
					gameState = 'guessing';
					statusText = 'You are the Guesser! Guess the drawing.';
				}
				gameOverInfo = null; // Clear previous game over info
				whiteboardKey = Date.now(); // Force whiteboard reset for the new game
				break;
			case 'drawEvent':
				// Forward drawing events to the Whiteboard component if the current player is the guesser
				if (gameState === 'guessing' && whiteboardComponent) {
					// Call the public method on the Whiteboard instance
					whiteboardComponent.handleDrawEvent(message.payload);
				}
				break;
			case 'guessResult':
				// Update status message for the guesser after an incorrect guess
				if (gameState === 'guessing') {
					statusText = `Guess '${message.payload.guess}': Incorrect. Keep trying!`;
					// Could add more sophisticated feedback (e.g., temporary highlight)
				}
				break;
			case 'gameOver':
				// Handle the end of the game
				gameState = 'gameOver';
				gameOverInfo = message.payload; // Store result { correct: bool, word: string }
				// Display appropriate game over message based on role and outcome
				if (playerRole === 'guesser' && message.payload.correct) {
					statusText = `Correct! The word was "${message.payload.word}". Game Over!`;
				} else if (playerRole === 'drawer' && message.payload.correct) {
					statusText = `The word "${message.payload.word}" was guessed! Game Over!`;
				} else {
					// Handle other game over scenarios (e.g., opponent disconnect handled by 'playerLeft')
					statusText = `Game Over! The word was "${message.payload.word}".`;
				}
				// Future enhancement: Add a "Play Again" button here, which could send a message to the backend.
				break;
			case 'playerLeft':
				// Handle opponent disconnection
				gameState = 'waiting'; // Return to waiting state
				statusText = 'Your opponent disconnected. Waiting for a new player...';
				// Reset player-specific states
				playerRole = null;
				secretWord = '';
				wordLength = 0;
				gameOverInfo = null;
				whiteboardKey = Date.now(); // Force whiteboard reset
				break;
			case 'error':
				// Display errors sent from the backend
				statusText = `Server Error: ${message.payload.message}`;
				// Consider resetting state based on error severity
				break;
			default:
				// Log unhandled message types for debugging
				console.warn("Received unhandled message type in App.svelte:", message.type);
		}
	}

	// --- Event Handlers from Child Components ---

	/**
	 * Handles the 'draw' event dispatched from the Whiteboard component.
	 * Sends the drawing data to the backend if the player is the drawer.
	 * @param {object} drawData - The drawing event details from Whiteboard.
	 */
	function handleDraw(drawData) {
		if (gameState === 'drawing') {
			sendMessage('drawEvent', drawData);
		}
	}

	/**
	 * Handles the 'guess' event dispatched from the GuessInput component.
	 * Sends the guess to the backend if the player is the guesser.
	 * @param {string} guess - The guess string from GuessInput.
	 */
	function handleGuess(guess) {
		if (gameState === 'guessing') {
			sendMessage('guess', { guess: guess });
		}
	}

	// --- Utility Functions ---

	/**
	 * Generates a string of underscores representing the word length for the guesser.
	 * @param {number} length - The length of the secret word.
	 * @returns {string} A string of underscores separated by spaces.
	 */
	function getWordBlanks(length) {
		if (length <= 0) return '';
		return Array(length).fill('_').join(' ');
	}

</script>

<main class="flex flex-col items-center justify-center min-h-screen bg-gray-100 p-4 font-sans">
	<h1 class="text-3xl font-bold mb-4 text-blue-600">Simple Scribblio</h1>

	{#if $wsConnected}
		<div class="w-full max-w-2xl bg-white shadow-lg rounded-lg p-6">
			<div class="mb-4 text-center">
				{#if playerRole === 'drawer'}
					<WordDisplay word={secretWord} />
				{:else if playerRole === 'guesser'}
					<WordDisplay blanks={getWordBlanks(wordLength)} length={wordLength}/>
				{:else}
					<div class="h-8"></div>
				{/if}
			</div>

			<div class="mb-4 border-2 border-black rounded overflow-hidden aspect-video bg-white">
				{#key whiteboardKey}
					<Whiteboard
						bind:this={whiteboardComponent} isDrawer={playerRole === 'drawer'} on:draw={event => handleDraw(event.detail)} />
				{/key}
			</div>

			<div class="mb-4 text-center">
				<StatusMessage message={statusText} /> </div>

			{#if playerRole === 'guesser' && gameState === 'guessing'}
				<GuessInput on:guess={event => handleGuess(event.detail)} /> {/if}

			{#if gameState === 'gameOver' && gameOverInfo}
				<div
					class="mt-4 p-4 rounded text-center"
					class:bg-green-100={gameOverInfo.correct} class:text-green-700={gameOverInfo.correct}
					class:bg-red-100={!gameOverInfo.correct} class:text-red-700={!gameOverInfo.correct}
				>
					<p class="font-semibold">Game Over!</p>
					<p>The word was: <span class="font-bold">{gameOverInfo.word}</span></p>
					</div>
			{/if}
		</div>
	{:else}
		<StatusMessage message={statusText} />
	{/if}
</main>

<style>
	/* Using Tailwind utility classes primarily, but global styles can go here */
	/* Example: */
	/* :global(body) { */
	/* font-family: 'Inter', sans-serif; */
	/* } */
</style>
